// Paleta e estilos base compartilhados por todas as paginas,
// para manter o mesmo visual do Dashboard (sidebar navy + destaque petroleo).

export const cores = {
  navy: '#16232E',
  navySecundario: '#20303D',
  navyBorda: '#24333F',
  teal: '#2F8F7A',
  tealFundo: '#E7F2EF',
  fundoPagina: '#F5F7FA',
  branco: '#FFFFFF',
  borda: '#E3E7EC',
  texto: '#16232E',
  textoSecundario: '#8A94A0',
  textoTerciario: '#6B7785',
  textoClaro: '#9BA8B5',
  sucesso: '#2F8F7A',
  sucessoFundo: '#E7F2EF',
  sucessoTexto: '#1F6B59',
  perigo: '#C0524A',
  perigoFundo: '#FBEAE8',
  perigoTexto: '#8C2F28',
  aviso: '#D6893F',
  avisoFundo: '#FBF1E6',
  avisoTexto: '#8A5522',
};

export const estilosBase = {
  pagina: {
    minHeight: '100vh',
    backgroundColor: cores.fundoPagina,
  },
  container: {
    padding: '36px 40px',
    boxSizing: 'border-box',
  },
  cabecalho: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    marginBottom: '24px',
  },
  titulo: {
    fontSize: '20px',
    fontWeight: '700',
    color: cores.texto,
    margin: 0,
  },
  subtitulo: {
    fontSize: '14px',
    fontWeight: '700',
    color: cores.texto,
    marginBottom: '14px',
  },
  card: {
    backgroundColor: cores.branco,
    border: '1px solid ' + cores.borda,
    borderRadius: '10px',
    padding: '24px',
  },
  label: {
    display: 'block',
    marginBottom: '6px',
    fontWeight: '600',
    color: cores.texto,
    fontSize: '13px',
  },
  labelPequeno: {
    display: 'block',
    marginBottom: '4px',
    fontWeight: '600',
    color: cores.textoSecundario,
    fontSize: '11.5px',
  },
  input: {
    width: '100%',
    padding: '11px 12px',
    border: '1px solid ' + cores.borda,
    borderRadius: '8px',
    fontSize: '14px',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    color: cores.texto,
    backgroundColor: cores.branco,
  },
  botaoPrimario: {
    padding: '13px 20px',
    backgroundColor: cores.teal,
    color: cores.branco,
    border: 'none',
    borderRadius: '8px',
    fontSize: '14.5px',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  botaoSecundario: {
    padding: '10px 16px',
    backgroundColor: cores.branco,
    color: cores.texto,
    border: '1px solid ' + cores.borda,
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  botaoPerigo: {
    padding: '11px 18px',
    backgroundColor: cores.perigo,
    color: cores.branco,
    border: 'none',
    borderRadius: '8px',
    fontSize: '13.5px',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  tag: {
    padding: '4px 11px',
    backgroundColor: cores.tealFundo,
    color: cores.teal,
    borderRadius: '20px',
    fontSize: '11.5px',
    fontWeight: '700',
  },
  erroBox: {
    backgroundColor: cores.perigoFundo,
    border: '1px solid ' + cores.perigo + '33',
    color: cores.perigoTexto,
    padding: '12px 14px',
    borderRadius: '8px',
    marginBottom: '18px',
    fontSize: '13.5px',
  },
  avisoBox: {
    backgroundColor: cores.avisoFundo,
    border: '1px solid ' + cores.aviso + '33',
    color: cores.avisoTexto,
    padding: '12px 14px',
    borderRadius: '8px',
    marginBottom: '14px',
    fontSize: '13px',
  },
  sucessoBox: {
    backgroundColor: cores.sucessoFundo,
    border: '1px solid ' + cores.teal + '33',
    color: cores.sucessoTexto,
    padding: '12px 14px',
    borderRadius: '8px',
    marginBottom: '14px',
    fontSize: '13px',
  },
  loadingBox: {
    textAlign: 'center',
    padding: '60px 20px',
    color: cores.textoSecundario,
    fontSize: '14px',
  },
  vazioBox: {
    backgroundColor: cores.branco,
    border: '1px solid ' + cores.borda,
    borderRadius: '10px',
    padding: '30px',
    textAlign: 'center',
    color: cores.textoSecundario,
    fontSize: '13.5px',
  },
};
